<?php return array(
    'root' => array(
        'name' => 'yiisoft/yii2-app-advanced',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'behat/gherkin' => array(
            'pretty_version' => 'v4.16.1',
            'version' => '4.16.1.0',
            'reference' => 'e26037937dfd48528746764dd870bc5d0836665f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'bower-asset/inputmask' => array(
            'pretty_version' => '5.0.9',
            'version' => '5.0.9.0',
            'reference' => '310a33557e2944daf86d5946a5e8c82b9118f8f7',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/inputmask',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => 'fde1f76e2799dd877c176abde0ec836553246991',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery-ui' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'reference' => '44ecf3794cc56b65954cc19737234a3119d036cc',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/punycode' => array(
            'pretty_version' => 'v2.3.1',
            'version' => '2.3.1.0',
            'reference' => '9e1b2cda98d215d3a73fcbfe93c62e021f4ba768',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/punycode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/yii2-pjax' => array(
            'pretty_version' => '2.0.9',
            'version' => '2.0.9.0',
            'reference' => '452b56b7124326487fd0d3be6b205fcaa66598a0',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/yii2-pjax',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cebe/markdown' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9bac5e971dd391e2802dca5400bbeacbaea9eb86',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cebe/markdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeception/codeception' => array(
            'pretty_version' => '5.3.4',
            'version' => '5.3.4.0',
            'reference' => 'cb4c200ec0a7fe21964f51872bb403701f53f35b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/codeception',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-asserts' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '06750a60af3ebc66faab4313981accec1be4eefc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-asserts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-innerbrowser' => array(
            'pretty_version' => '3.1.3',
            'version' => '3.1.3.0',
            'reference' => '10482f7e34c0537bf5b87bc82a3d65a1842a8b4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-innerbrowser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-web' => array(
            'pretty_version' => '1.0.7',
            'version' => '1.0.7.0',
            'reference' => '1444ccc9b1d6721f3ced8703c8f4a9041b80df93',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-web',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-yii2' => array(
            'pretty_version' => '1.1.12',
            'version' => '1.1.12.0',
            'reference' => '1ebe6bc2a7f307a6c246026a905612a40ef64859',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-yii2',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'codeception/stub' => array(
            'pretty_version' => '4.2.1',
            'version' => '4.2.1.0',
            'reference' => '0c573cd5c62a828dadadc41bc56f8434860bb7bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/verify' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '2f8f5ce6ea1be5c011f77eb7f1ca0c9f4d551513',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/verify',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'diggindata/yii2-countrylist' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '3a671f97dfd7d83452cc014fe429b7fced077aae',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../diggindata/yii2-countrylist',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'd42c8731f0624ad6bdc8d3e5e9a4524f68801cfa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.19.0',
            'version' => '4.19.0.0',
            'reference' => 'b287d2a16aceffbf6e0295559b39662612b77fcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.24.1',
            'version' => '1.24.1.0',
            'reference' => 'e0ee18eb1e6dc3cda3ce9fd97e5a0689a88a64b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => '8.13.55',
            'version' => '8.13.55.0',
            'reference' => '6e28b3d53cf96d7f41c83d9b80b6021ecbd00537',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/libphonenumber-for-php-lite' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.13.55',
            ),
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '1cd8b3ad2d43e04f4c2c6a240495af44780f809b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '21dc724a0583619cd1652f673303492272778051',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'karataserkan/yii2-multi-dataprovider' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'da9969ca5c67a6da8d1d5f7f2e84f0d0abb5ba2b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../karataserkan/yii2-multi-dataprovider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-fileinput' => array(
            'pretty_version' => 'v5.5.4',
            'version' => '5.5.4.0',
            'reference' => '8de1bed638823c70272b2578847e2b31e42677ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-fileinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-popover-x' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'reference' => '879def62529797833e10885b6e77864e83e9e240',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-popover-x',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-bootstrap5-dropdown' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '459e4c06c64e49f89ac372ce7c2cabb961f56ec9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-bootstrap5-dropdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-builder' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '616c2f8d322a45c037a4d32f0ee1eb1457865e73',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-builder',
            'aliases' => array(
                0 => '1.6.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-date-range' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '99f37fa14b8e7c99ca538377191c12502002f5d2',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-date-range',
            'aliases' => array(
                0 => '1.7.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dialog' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '510c3a35ffe79987cde9a9366cedbff545fd92d4',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dialog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dynagrid' => array(
            'pretty_version' => 'v1.5.5',
            'version' => '1.5.5.0',
            'reference' => '4d81fda0775a2994df3d863b1259dc5edf1e8952',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dynagrid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-editable' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'ae4cc2384e667ba9dfe8bfb0098716caeb2500a8',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-editable',
            'aliases' => array(
                0 => '1.8.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-export' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5f0223ad175d0f85bdbaa44aff1ac93009f2cc1d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-export',
            'aliases' => array(
                0 => '1.4.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-field-range' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '8a18edb343b3beb96ddc86e4a06aee28be160787',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-field-range',
            'aliases' => array(
                0 => '1.3.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-grid' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'bcaacfc442b8c7ac97c00c52dfdb5f7ebdca4e0c',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-grid',
            'aliases' => array(
                0 => '3.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-helpers' => array(
            'pretty_version' => 'v1.3.9',
            'version' => '1.3.9.0',
            'reference' => '0bec7a97bf9d0293d96be5c496fe9654c4dec94b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-helpers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-krajee-base' => array(
            'pretty_version' => 'v3.0.5',
            'version' => '3.0.5.0',
            'reference' => '5c095126d1be47e0bb1f92779b7dc099f6feae31',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-krajee-base',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-mpdf' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '6a6506e680e4a07b1781da12bed9c080263f5f4a',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-mpdf',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-popover-x' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'b0320d1315bbfce31ec8907882c6f4abed223a28',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-popover-x',
            'aliases' => array(
                0 => '1.3.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-sortable' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'a6f9a9adb873d6345de92bbe5e436ac1a1db30bc',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-sortable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-validators' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'bd5c771232b556fe7920a22e6705f03e6747b8f5',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-validators',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-activeform' => array(
            'pretty_version' => 'v1.6.4',
            'version' => '1.6.4.0',
            'reference' => '697407c8fa9c81593a7bb9bef4b7ad53f7d38b79',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-activeform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-colorinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '377873eb28a173501550e99fb13f0cb4c88f6329',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-colorinput',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datepicker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'a42d8f56efa4e37af609c466c6133acab1a5c21e',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datepicker',
            'aliases' => array(
                0 => '1.4.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datetimepicker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '85b22d38553ca207f86be198f37e6531347e9a23',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datetimepicker',
            'aliases' => array(
                0 => '1.5.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-fileinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'b5500b6855526837154694c2afab8dbc3afc8abd',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-fileinput',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-growl' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '80b4a4da28b59e95b909b24b4aa5d6eb1765d2c9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-growl',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-select2' => array(
            'pretty_version' => 'v2.2.5',
            'version' => '2.2.5.0',
            'reference' => '4b8ef7dd9780531fc997fa23a53a38a1f7674bec',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-select2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-sidenav' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5d3276503d224f73c34f1010d6bc6dd4e936c50f',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-sidenav',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-spinner' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'db22bd63fd1c1d3f9d8aa9477842f16338050ff1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-spinner',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-switchinput' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '10afe2ac8274da9371b43aaf69e99fc553f1b947',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-switchinput',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-touchspin' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '1eec4c3f3a8bf9a170e1e0682c2c89f2929d65e9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-touchspin',
            'aliases' => array(
                0 => '1.2.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'koolreport/core' => array(
            'pretty_version' => '6.6.7',
            'version' => '6.6.7.0',
            'reference' => '7703f9e8b92fff4caca77251d11094c2047b0c75',
            'type' => 'library',
            'install_path' => __DIR__ . '/../koolreport/core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '682f1098a8fddbaf43edac2306a691c7ad508ec5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => 'fcf91eb64359852f00d921887b219479b4f21251',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.2.7',
            'version' => '8.2.7.0',
            'reference' => 'b59670a09498689c33ce639bac8f5ba26721dab3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/psr-http-message-shim' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'f25a0153d645e234f9db42e5433b16d9b113920f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/psr-http-message-shim',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/psr-log-aware-trait' => array(
            'pretty_version' => 'v3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'a633da6065e946cc491e1c962850344bb0bf3e78',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/psr-log-aware-trait',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.13.4',
            'version' => '1.13.4.0',
            'reference' => '07d290f0c47959fd5eed98c95ee5602db07e0b6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.7.0',
            'version' => '5.7.0.0',
            'reference' => 'dca41cd15c2ac9d055ad70dbfd011130757d1f82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '5.4.0',
            'version' => '5.4.0.0',
            'reference' => '48f2fe37d64c2dece0ef71fb2ac55497566782af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.32',
            'version' => '9.2.32.0',
            'reference' => '85402a822d1ecf1db1096959413d35e1c37cf1a5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.28',
            'version' => '9.5.28.0',
            'reference' => '954ca3113a03bf780d22f07bf055d883ee04b65e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.12.18',
            'version' => '0.12.18.0',
            'reference' => 'ddff0ac01beddc251786fe70367cd8bbdb258196',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '2b56bea83a09de3ac06bb18b92f068e60cc6f50b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.10',
            'version' => '4.0.10.0',
            'reference' => 'e4df00b9b3571187db2831ae9aada2c6efbd715d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '25f207c40d62b8b7aa32f5ab026c53561964053a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => 'ba01945089c3a293b01ba9badc29ad55b106b0bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.5',
            'version' => '5.1.5.0',
            'reference' => '830c43a844f1f8d5b7a1f6d6076b784454d8b7ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.8',
            'version' => '4.0.8.0',
            'reference' => '14c6ba52f95a36c3d27c835d65efc7123c446e8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.8',
            'version' => '5.0.8.0',
            'reference' => 'b6781316bdcd28260904e7cc18ec983d0d2ef4f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'e1e4a170560925c26d424b6a03aed157e7dcc5c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => '539c6691e0623af6dc6f9c20384c120f963465a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => '05d5692a7993ecccd56a03e40cd7e5b09b1d404e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'select2/select2' => array(
            'pretty_version' => '4.0.13',
            'version' => '4.0.13.0',
            'reference' => '45f2b83ceed5231afa7b3d5b12b58ad335edd82e',
            'type' => 'component',
            'install_path' => __DIR__ . '/../select2/select2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.6.4',
            'version' => '2.6.4.0',
            'reference' => '4b53852fde2734ec6a07e458a085db627c60eada',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sjaakp/yii2-alphapager' => array(
            'pretty_version' => '1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'a1c93bc049329a9a39f422ca7d4faca5a2821058',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sjaakp/yii2-alphapager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sjaakp/yii2-datepager' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'ab2d5ea5ddc1ca281eb64fbb620300c09203599b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sjaakp/yii2-datepager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sjaakp/yii2-gcharts' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '685bd0fc0a7a95d160b501545b16a1f03d5fb4b4',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sjaakp/yii2-gcharts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sjaakp/yii2-helpers' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '5bddfc29fc7199b347ab97d4f79ace90a52a8c25',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sjaakp/yii2-helpers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v6.4.32',
            'version' => '6.4.32.0',
            'reference' => 'f49947cf0cbd7d685281ef74e05b98f5e75b181f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '41e38717ac1dd7a46b6bda7d6a82af2d98a78894',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v7.4.0',
            'version' => '7.4.0.0',
            'reference' => 'ab862f478513e7ca2fe9ec117a6f01a8da6e1135',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '63afe740e99a13ba87ec199bb07bbdee937a5b62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v6.4.32',
            'version' => '6.4.32.0',
            'reference' => 'f57f1cbd6b13b54e7f8a25cae1ee55cbe892b1f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => 'dc2c0eba1af673e736bb851d747d266108aea746',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '59eb412e93815df44f05f342958efa9f46b1e586',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '01b24a145bbeaa7141e75887ec904c34a6728a5f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '7b750074c40c694ceb34cb926d6dffee231c5cd6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '40945014c0a9471ccfe19673c54738fa19367a3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'a3cc8b044a6ea513310cbd48ef7333b384945638',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '380872130d3a5dd3ace2f4010d95125fde5d5c70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '9614ac4d8061dc257ecc64cba1b140873dce8ad3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '3833d7255cc303546435cb650316bff708a1c75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '45112560a3ba2d715666a509a0bc9521d10b6c43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '1c4b10461bf2ec27537b5f36105337262f5f5d6f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.4.4',
            'version' => '7.4.4.0',
            'reference' => '0e4769b46a0c3c62390d124635ce59f66874b282',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v7.4.1',
            'version' => '7.4.1.0',
            'reference' => '24dd4de28d2e3988b311751ac49e684d783e2345',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.10.1',
            'version' => '6.10.1.0',
            'reference' => '7a2701251e5d52fc3d508fd71704683eb54f5939',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'b7489ce515e168639d17feec34b8847c326b0b3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twbs/bootstrap' => array(
            'pretty_version' => 'v5.3.8',
            'version' => '5.3.8.0',
            'reference' => '25aa8cc0b32f0d1a54be575347e6d84b70b1acd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twbs/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twitter/bootstrap' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.3.8',
            ),
        ),
        'umpirsky/country-list' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '4d8f87526c891a7b110b530eabf910c3f7468ad6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../umpirsky/country-list',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2' => array(
            'pretty_version' => '2.0.54',
            'version' => '2.0.54.0',
            'reference' => '99daebf2de0b031d129706a5db6ce0802c70bac9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yiisoft/yii2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-app-advanced' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap5' => array(
            'pretty_version' => '2.0.51',
            'version' => '2.0.51.0',
            'reference' => '23675f617ee3c86cf3e65a31a6afbc75e13028cb',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-composer' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'reference' => 'b684b01ecb119c8287721def726a0e24fec2fef2',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../yiisoft/yii2-composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-debug' => array(
            'pretty_version' => '2.1.27',
            'version' => '2.1.27.0',
            'reference' => '44e158914911ef81cd7111fd6d46b918f65fae7c',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-debug',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-faker' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => '8c361657143bfaea58ff7dcc9bf51f1991a46f5d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-gii' => array(
            'pretty_version' => '2.2.7',
            'version' => '2.2.7.0',
            'reference' => 'f17c7ef7ef3081213f612b37ad0ceaa8e8cd3d3b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-gii',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-jui' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'reference' => 'ce45c16d4fbbe7d1c516d8d0e8311e07f6138eed',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-jui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-symfonymailer' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '291c00979a9bf14e89bb5230ddd700a6dc130e51',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-symfonymailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
